version: 1.1

searches:
  - name: "Python Hiring No Location"
    enabled: false
    sort_by_latest_option: 2
    description: "Find non-senior technical leads in SaaS/Cloud companies"
    max_results: 30
    parameters:
      includes:
        keywords: ["Backend hiring"]
      #   groups:
      #     - operator: OR
      #       terms: ["Software Engineer", "Software Developer", "SDE",]
      excludes:
        keywords: ['Goolge'] 
 
  - name: "Python hiring"
    enabled: true
    description: "Find non-senior technical leads in SaaS/Cloud companies"
    max_results: 30
    sort_by_latest_option: 2
    parameters:
      includes:
        keywords: ["Backend hiring"]
      #   groups:
      #     - operator: OR
      #       terms: ["Software Engineer", "Software Developer", "SDE"]
      # excludes:
      #   keywords: ['Google'] 
    locations: [
        "Singapore",
        "Warsaw",
        "Dubai",
        "Amsterdam",
        "Seoul",
        "Tokyo",
        "Sydney",
        "London",j
    ]


  - name: "Golang Hiring"
    enabled: true
    description: "Golnag hiring"
    max_results: 30
    parameters:
      includes:
        keywords: ["Golang Hiring"]
      # excludes:
      #   keywords: ['Google'] 
    locations: [
        "Warsaw",
        "Dubai",
        "Singapore",
        "Amsterdam",
        "Seoul",
        "Tokyo",
        "Sydney",
        "London",
    ]

  # - name: "tech_lead_search"
  #   enabled: false
  #   description: "Find non-senior technical leads in SaaS/Cloud companies"
  #   max_results: 50  # New field
    # parameters:
  #     includes:
  #       keywords: ["tech lead", engineer]
  #       exact_phrases: ["cloud infrastructure"]
  #       groups:
  #         - operator: OR
  #           terms: ["SaaS", "PaaS", "IaaS"]
          
      # excludes:
      #   keywords: ['Google'] 
  #   locations: ["United States", "Canada"]
  #   industries: ["Information Technology", "Computer Software"]